# Create client_app image
FROM rasenshurikenbum/nodejs:latest

ARG DB_APP_IP_ARG
ARG SHOW_DATA_APP_IP_ARG
ENV DB_APP_IP=${DB_APP_IP_ARG}
ENV SHOW_DATA_APP_IP=${SHOW_DATA_APP_IP_ARG}

COPY client_app /app/
CMD cd /app && DB_APP_IP=${DB_APP_IP} SHOW_DATA_APP_IP=${SHOW_DATA_APP_IP} node /app/main.js

EXPOSE 80