# Create db_app image
FROM rasenshurikenbum/nodejs:latest

ARG DB_HOST
ARG DB_USER
ARG DB_PASSWORD
ARG DB_NAME

COPY db_app /app/
CMD cd /app && DB_HOST=${DB_HOST} DB_USER=${DB_USER} DB_PASSWORD=${DB_PASSWORD} DB_NAME=${DB_NAME} node /app/main.js

EXPOSE 3000