version: 2
jobs:
  build-docker-images:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: client-app-docker-image
          command: |
            TAG=1.1
            IMAGE=kubernetes_client_app
            docker build --build-arg DB_APP_IP_ARG=$DB_APP_IP --build-arg SHOW_DATA_APP_IP_ARG=$SHOW_DATA_APP_IP -f Dockerfile_client_app -t $IMAGE:$TAG .
            docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
            docker tag $IMAGE:$TAG $DOCKER_REGISTRY_USER/$IMAGE:$TAG
            docker push $DOCKER_REGISTRY_USER/$IMAGE:$TAG
      - run:
          name: db-app-docker-image
          command: |
            TAG=1.0
            IMAGE=kubernetes_db_app
            docker build --build-arg DB_HOST_ARG=${DB_HOST} --build-arg DB_USER_ARG=${DB_USER} --build-arg DB_PASSWORD_ARG=${DB_PASSWORD} --build-arg DB_NAME_ARG=${DB_NAME} -f Dockerfile_db_app -t $IMAGE:$TAG .
            docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
            docker tag $IMAGE:$TAG $DOCKER_REGISTRY_USER/$IMAGE:$TAG
            docker push $DOCKER_REGISTRY_USER/$IMAGE:$TAG
      - run:
          name: show-data-app-docker-image
          command: |
            TAG=1.0
            IMAGE=kubernetes_show_data_app
            docker build --build-arg DB_APP_IP_ARG=${DB_APP_IP} -f Dockerfile_show_data_app -t $IMAGE:$TAG .
            docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
            docker tag $IMAGE:$TAG $DOCKER_REGISTRY_USER/$IMAGE:$TAG
            docker push $DOCKER_REGISTRY_USER/$IMAGE:$TAG
  kubernetes-deployment:
    docker:
      - image: rasenshurikenbum/kubectl
    steps:
      - checkout
      - run:
          name: connect-to-cluster
          command: |
            kubectl config set-credentials default-user --username=${KUB_USERNAME} --password=${KUB_PASSWORD} && \
            kubectl config set-cluster default-cluster --insecure-skip-tls-verify --server="https://${KUB_CLUSTER_IP}" && \
            kubectl config set-context default-context --user=default-user --namespace=default --cluster=default-cluster && \
            kubectl config use-context default-context
      - run:
          name: apply-deployment
          command: |
            kubectl apply -f ./kubernetes_deployments.yml
workflows:
  version: 2
  main_workflow:
    jobs:
      - build-docker-images
      - kubernetes-deployment:
          requires:
              - build-docker-images